apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-tasks
  namespace: app
  annotations:
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: get-tasks=acrtodoappdev01.azurecr.io/microtodogettask
    argocd-image-updater.argoproj.io/get-tasks.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-tasks
  template:
    metadata:
      labels:
        app: get-tasks
    spec:
      imagePullSecrets:
        - name: acr-creds
      containers:
      - name: get-tasks
        image: acrtodoappdev01.azurecr.io/microtodogettask:11
        imagePullPolicy: Always
        env:
          - name: CONNECTION_STRING
            value: "Driver={Driver={ODBC Driver 18 for SQL Server};Server=tcp:mssqldbserverdev.database.windows.net,1433;Database=sqldbdev;Uid=sqladminuser;Pwd=Test@12345;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
        ports:
          - containerPort: 8000
