apiVersion: v1
kind: Secret
metadata:
  name: dbdetails
type: Opaque
data:
  CONNECTION_STRING: RHJpdmVyPXtPREJDIERyaXZlciAxOCBmb3IgU1FMIFNlcnZlcn07U2VydmVyPXRjcDptc3NxbGRic2VydmVyZGV2LmRhdGFiYXNlLndpbmRvd3MubmV0LDE0MzM7RGF0YWJhc2U9c3FsZGJkZXY7VWlkPXNxbGFkbWludXNlcjtQd2Q9VGVzdEAxMjM0NTtFbmNyeXB0PXllcztUcnVzdFNlcnZlckNlcnRpZmljYXRlPW5vO0Nvbm5lY3Rpb24gVGltZW91dD0zMDs=

